import { useState } from 'react';
import { Link, router } from 'expo-router';
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { api } from '../../src/api';
import { palette, radius } from '../../src/theme';
import { BrandLockup, Field, PrimaryButton, ScreenHeading } from '../../src/ui';
const roles=[{value:'buyer',label:'BUYER',copy:'Find and license sound',icon:'♪'},{value:'creator',label:'CREATOR',copy:'Sell beats and grow',icon:'♫'},{value:'artist',label:'ARTIST',copy:'Build your next release',icon:'★'}] as const;
export default function Signup(){
 const [stageName,setStageName]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [role,setRole]=useState<'buyer'|'creator'|'artist'>('buyer');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(){setError('');if(!stageName.trim()||!email.trim()||password.length<8){setError('Enter your name, a valid email and a password of at least 8 characters.');return;}setBusy(true);try{await api('/auth/signup',{method:'POST',body:JSON.stringify({stage_name:stageName.trim(),email:email.trim(),password,role})});router.replace({pathname:'/(auth)/verify-email',params:{email:email.trim().toLowerCase()}});}catch(e){setError(e instanceof Error?e.message:'Unable to create account.');}finally{setBusy(false);}}
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled"><BrandLockup compact/><View style={s.heading}><ScreenHeading kicker="JOIN THE CULTURE" title="Create your BeatHub." copy="One account across web and mobile. Choose how you want to start."/></View><View style={s.roles}>{roles.map(item=><Pressable key={item.value} onPress={()=>setRole(item.value)} style={[s.role,role===item.value&&s.roleActive]}><Text style={[s.roleIcon,role===item.value&&s.roleIconActive]}>{item.icon}</Text><Text style={[s.roleLabel,role===item.value&&s.roleLabelActive]}>{item.label}</Text><Text style={s.roleCopy}>{item.copy}</Text></Pressable>)}</View><View style={s.form}><Text style={s.label}>STAGE OR DISPLAY NAME</Text><Field placeholder="How people will know you" value={stageName} onChangeText={setStageName}/><Text style={s.label}>EMAIL ADDRESS</Text><Field placeholder="you@example.com" autoCapitalize="none" keyboardType="email-address" value={email} onChangeText={setEmail}/><Text style={s.label}>PASSWORD</Text><Field placeholder="8+ characters" secureTextEntry value={password} onChangeText={setPassword}/>{!!error&&<Text style={s.error}>{error}</Text>}<PrimaryButton label="CREATE MY ACCOUNT" icon="→" onPress={submit} busy={busy}/></View><Link href="/(auth)/login" style={s.link}>Already on BeatHub? Sign in</Link></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:palette.canvas},container:{padding:22,paddingBottom:40},heading:{marginTop:28},roles:{flexDirection:'row',gap:8,marginTop:22},role:{flex:1,minHeight:116,padding:12,borderRadius:radius.md,backgroundColor:palette.surface,borderWidth:1,borderColor:palette.border},roleActive:{borderColor:palette.gold,backgroundColor:'#201812'},roleIcon:{color:palette.muted2,fontSize:22,fontWeight:'900'},roleIconActive:{color:palette.gold},roleLabel:{color:palette.muted,fontSize:9,fontWeight:'900',letterSpacing:1,marginTop:10},roleLabelActive:{color:palette.goldBright},roleCopy:{color:palette.muted2,fontSize:10,lineHeight:14,marginTop:5},form:{gap:10,marginTop:22},label:{color:palette.muted,fontSize:9,fontWeight:'900',letterSpacing:1.3,marginTop:5},error:{color:palette.danger,lineHeight:19,fontSize:12},link:{color:palette.white,textAlign:'center',marginTop:22,fontWeight:'800'}});
