import { useCallback, useState } from 'react';
import { router, useFocusEffect } from 'expo-router';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { api } from '../src/api';

type Profile={stage_name:string;slug:string;bio?:string|null;instagram_url?:string|null;twitter_url?:string|null;youtube_url?:string|null;website_url?:string|null;store_url:string};

export default function CreatorProfile(){
 const [profile,setProfile]=useState<Profile|null>(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState(''); const [saved,setSaved]=useState(false);
 const load=useCallback(async()=>{setError('');try{setProfile(await api<Profile>('/creator/profile'));}catch(e){setError(e instanceof Error?e.message:'Unable to load profile.');}finally{setLoading(false);}},[]);
 useFocusEffect(useCallback(()=>{load();},[load]));
 const update=(key:keyof Profile,value:string)=>setProfile(p=>p?{...p,[key]:value}:p);
 const save=async()=>{if(!profile)return;setSaving(true);setError('');setSaved(false);try{const r=await api<{profile:Profile}>('/creator/profile',{method:'PATCH',body:JSON.stringify({stage_name:profile.stage_name,bio:profile.bio||null,instagram_url:profile.instagram_url||null,twitter_url:profile.twitter_url||null,youtube_url:profile.youtube_url||null,website_url:profile.website_url||null})});setProfile(r.profile);setSaved(true);}catch(e){setError(e instanceof Error?e.message:'Unable to save profile.');}finally{setSaving(false);}};
 if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator/><Text style={s.muted}>Loading profile…</Text></View></SafeAreaView>;
 if(!profile)return <SafeAreaView style={s.safe}><View style={s.container}><Text style={s.title}>Creator profile</Text><Text style={s.error}>{error||'Profile unavailable.'}</Text></View></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={s.eyebrow}>CREATOR PROFILE</Text><Text style={s.title}>Your public identity</Text><Text style={s.muted}>This information appears on your BeatHub creator store.</Text>
  <Text style={s.label}>Stage name</Text><TextInput value={profile.stage_name} onChangeText={v=>update('stage_name',v)} style={s.input} placeholder="Stage name" placeholderTextColor="#6f6978" maxLength={120}/>
  <Text style={s.label}>Bio</Text><TextInput value={profile.bio||''} onChangeText={v=>update('bio',v)} style={[s.input,s.bio]} placeholder="Tell artists about yourself" placeholderTextColor="#6f6978" multiline maxLength={5000}/>
  {([['instagram_url','Instagram'],['twitter_url','X / Twitter'],['youtube_url','YouTube'],['website_url','Website']] as const).map(([key,label])=><View key={key}><Text style={s.label}>{label}</Text><TextInput value={profile[key]||''} onChangeText={v=>update(key,v)} style={s.input} placeholder={`https://${label.toLowerCase().replace(/[^a-z]/g,'')}.com/...`} placeholderTextColor="#6f6978" autoCapitalize="none" keyboardType="url"/></View>)}
  {error?<Text style={s.error}>{error}</Text>:null}{saved?<Text style={s.success}>Profile saved.</Text>:null}<Pressable disabled={saving} style={s.button} onPress={save}>{saving?<ActivityIndicator/>:<Text style={s.buttonText}>Save profile</Text>}</Pressable><Text style={s.label}>Public store</Text><Text style={s.store}>{profile.store_url}</Text><Pressable style={s.secondary} onPress={()=>router.push('/(tabs)/beats')}><Text style={s.secondaryText}>Back to marketplace</Text></Pressable>
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#0d0b12'},container:{padding:22,paddingBottom:45},center:{flex:1,alignItems:'center',justifyContent:'center'},back:{color:'#fff',fontSize:16,marginBottom:20},eyebrow:{color:'#918b9b',fontSize:12,fontWeight:'800',letterSpacing:1.5},title:{color:'#fff',fontSize:30,fontWeight:'800',marginTop:7},muted:{color:'#918b9b',fontSize:15,lineHeight:21,marginTop:7,marginBottom:20},label:{color:'#c8c1d0',fontSize:13,fontWeight:'700',marginTop:17,marginBottom:7},input:{backgroundColor:'#181520',borderRadius:12,color:'#fff',padding:14,fontSize:15,borderWidth:1,borderColor:'#2b2633'},bio:{minHeight:120,textAlignVertical:'top'},button:{backgroundColor:'#fff',borderRadius:12,padding:15,alignItems:'center',marginTop:24},buttonText:{color:'#0d0b12',fontWeight:'800'},secondary:{borderWidth:1,borderColor:'#302b38',borderRadius:12,padding:14,alignItems:'center',marginTop:12},secondaryText:{color:'#fff',fontWeight:'700'},store:{color:'#a9a1b2',fontSize:13},error:{color:'#ff8f8f',marginTop:15},success:{color:'#8ee0a8',marginTop:15}})
