import { useCallback, useState } from 'react';
import { router, useFocusEffect } from 'expo-router';
import { ActivityIndicator, Alert, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { api } from '../src/api';

type Sale={id:string;order_number:string;track_title:string;gross_amount:number;commission_amount:number;net_amount:number;currency:string;completed_at:string|null};
type Withdrawal={id:string;amount:number;currency:string;phone_number:string;status:string;admin_note:string|null;created_at:string|null;resolved_at:string|null};
type CurrencyStats={sales:number;gross:number;commission:number;net:number;available:number;pending_withdrawal:number};
type Summary={currencies:Record<string,CurrencyStats>;minimum_withdrawal?:number;next_payout?:string};

export default function CreatorFinances(){
 const [sales,setSales]=useState<Sale[]>([]); const [withdrawals,setWithdrawals]=useState<Withdrawal[]>([]); const [summary,setSummary]=useState<Summary|null>(null);
 const [amount,setAmount]=useState(''); const [phone,setPhone]=useState(''); const [submitting,setSubmitting]=useState(false);
 const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false); const [error,setError]=useState('');
 const load=useCallback(async()=>{setError('');try{const [salesResult,withdrawalResult,summaryResult]=await Promise.all([api<{items:Sale[]}>('/creator/sales'),api<{items:Withdrawal[]}>('/creator/withdrawals'),api<Summary>('/creator/financial-summary')]);setSales(salesResult.items);setWithdrawals(withdrawalResult.items);setSummary(summaryResult);}catch(e){setError(e instanceof Error?e.message:'Unable to load creator finances.');}finally{setLoading(false);setRefreshing(false);}},[]);
 useFocusEffect(useCallback(()=>{load();},[load]));
 const requestWithdrawal=async()=>{const value=Number(amount);const minimum=summary?.minimum_withdrawal??500;if(!Number.isFinite(value)||value<minimum){setError(`Minimum withdrawal is KES ${minimum}.`);return;}if(!phone.trim()){setError('Enter the M-Pesa phone number that should receive the payout.');return;}setSubmitting(true);setError('');try{const r=await api<{message:string}>('/creator/withdrawals',{method:'POST',body:JSON.stringify({amount:value,phone_number:phone.trim()})});setAmount('');Alert.alert('Withdrawal requested',r.message);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to request withdrawal.');}finally{setSubmitting(false);}};
 if(loading)return <SafeAreaView style={s.safe}><View style={s.center}><ActivityIndicator/><Text style={s.muted}>Loading finances…</Text></View></SafeAreaView>;
 const kes=summary?.currencies?.KES; const minimum=summary?.minimum_withdrawal??500;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load();}} />}>
  <Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Creator Studio</Text></Pressable><Text style={s.eyebrow}>CREATOR FINANCES</Text><Text style={s.title}>Sales & withdrawals</Text>{error?<Text style={s.error}>{error}</Text>:null}
  <View style={s.balance}><Text style={s.label}>Available KES</Text><Text style={s.balanceValue}>KSh {Number(kes?.available||0).toFixed(2)}</Text><Text style={s.muted}>Minimum withdrawal: KSh {minimum.toFixed(0)}{summary?.next_payout?` · Next payout ${summary.next_payout}`:''}</Text></View>
  <Text style={s.section}>Request M-Pesa withdrawal</Text><TextInput style={s.input} value={amount} onChangeText={setAmount} keyboardType="decimal-pad" placeholder={`Amount (min KES ${minimum})`} placeholderTextColor="#777180"/><TextInput style={s.input} value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="M-Pesa number e.g. 0712345678" placeholderTextColor="#777180"/><Pressable style={s.button} disabled={submitting||Number(kes?.available||0)<minimum} onPress={requestWithdrawal}>{submitting?<ActivityIndicator/>:<Text style={s.buttonText}>Request withdrawal</Text>}</Pressable>
  <Text style={s.section}>Recent sales</Text>{sales.length===0?<Text style={s.muted}>No completed sales yet.</Text>:sales.map(x=><View key={x.id} style={s.card}><Text style={s.track}>{x.track_title||'Track'}</Text><Text style={s.meta}>{x.order_number} · {x.currency} {x.gross_amount.toFixed(2)}</Text><Text style={s.net}>Creator earnings: {x.currency} {x.net_amount.toFixed(2)}</Text></View>)}
  <Text style={s.section}>Withdrawal history</Text>{withdrawals.length===0?<Text style={s.muted}>No withdrawal requests yet.</Text>:withdrawals.map(x=><View key={x.id} style={s.card}><Text style={s.track}>{x.currency} {x.amount.toFixed(2)}</Text><Text style={s.meta}>{x.status.toUpperCase()} · +{x.phone_number}</Text>{x.admin_note?<Text style={s.note}>{x.admin_note}</Text>:null}</View>)}
 </ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#0d0b12'},container:{padding:22,paddingBottom:50},center:{flex:1,alignItems:'center',justifyContent:'center'},back:{color:'#aaa3b4',fontSize:15,marginTop:8,marginBottom:12},eyebrow:{color:'#918b9b',fontSize:12,fontWeight:'800',letterSpacing:1.5,marginTop:8},title:{color:'#fff',fontSize:30,fontWeight:'800',marginTop:7},section:{color:'#fff',fontSize:21,fontWeight:'800',marginTop:28,marginBottom:12},muted:{color:'#918b9b',fontSize:13,lineHeight:20,marginTop:6},error:{color:'#ff8f8f',marginTop:18},balance:{backgroundColor:'#181520',borderRadius:16,padding:18,marginTop:20},label:{color:'#918b9b',fontSize:12,fontWeight:'800'},balanceValue:{color:'#fff',fontSize:27,fontWeight:'800',marginTop:8},input:{backgroundColor:'#181520',borderRadius:12,padding:15,color:'#fff',marginBottom:10,borderWidth:1,borderColor:'#2b2633'},button:{backgroundColor:'#fff',borderRadius:12,padding:15,alignItems:'center'},buttonText:{color:'#0d0b12',fontWeight:'800'},card:{backgroundColor:'#181520',borderRadius:15,padding:16,marginBottom:10},track:{color:'#fff',fontSize:16,fontWeight:'800'},meta:{color:'#918b9b',marginTop:6},net:{color:'#fff',fontWeight:'700',marginTop:10},note:{color:'#c8c1d0',marginTop:8}});
