import { useEffect, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { ActivityIndicator, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { api, Track } from '../../src/api';

export default function BeatDetails(){const {slug}=useLocalSearchParams<{slug:string}>();const [track,setTrack]=useState<Track|null>(null);const [busy,setBusy]=useState(true);const [buying,setBuying]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{if(!slug)return;(async()=>{try{setTrack(await api<Track>(`/catalog/${encodeURIComponent(slug)}`))}catch(e){setError(e instanceof Error?e.message:'Unable to load track.')}finally{setBusy(false)}})()},[slug]);
 async function buy(){if(!track)return;setBuying(true);setError('');try{const r=await api<{order_id:string;authorization_url:string}>(`/payments/paystack/initialize`,{method:'POST',body:JSON.stringify({slug:track.slug})});router.push(`/checkout/${r.order_id}?url=${encodeURIComponent(r.authorization_url)}`)}catch(e){setError(e instanceof Error?e.message:'Unable to start checkout.')}finally{setBuying(false)}}
 if(busy)return <SafeAreaView style={s.safe}><ActivityIndicator/></SafeAreaView>;if(!track)return <SafeAreaView style={s.safe}><Text style={s.error}>{error||'Track not found.'}</Text></SafeAreaView>;
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><View style={s.art}><Text style={s.note}>♪</Text></View><Text style={s.title}>{track.title}</Text><Text style={s.producer}>{track.producer||'BeatHub Creator'}</Text><View style={s.meta}><Text style={s.metaText}>{track.genre||'Music'}</Text><Text style={s.metaText}>{track.bpm?`${track.bpm} BPM`:'Beat'}</Text><Text style={s.metaText}>{track.sales_model}</Text></View>{!!track.description&&<Text style={s.description}>{track.description}</Text>} {!!error&&<Text style={s.error}>{error}</Text>}<Pressable style={s.buy} onPress={buy} disabled={buying}>{buying?<ActivityIndicator/>:<Text style={s.buyText}>Buy · {track.currency} {track.price.toFixed(0)}</Text>}</Pressable></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#0d0b12'},container:{padding:22,paddingBottom:50},back:{color:'#aaa3b4',fontSize:16,marginVertical:12},art:{height:300,borderRadius:22,backgroundColor:'#211c29',alignItems:'center',justifyContent:'center',marginBottom:24},note:{fontSize:80,color:'#fff'},title:{fontSize:31,fontWeight:'800',color:'#fff'},producer:{fontSize:16,color:'#aaa3b4',marginTop:6},meta:{flexDirection:'row',gap:8,marginTop:18},metaText:{color:'#ddd6e4',backgroundColor:'#181520',padding:8,borderRadius:8,fontSize:12},description:{color:'#aaa3b4',lineHeight:23,marginTop:22},buy:{backgroundColor:'#fff',padding:17,borderRadius:13,alignItems:'center',marginTop:28},buyText:{fontWeight:'800',color:'#0d0b12'},error:{color:'#ff8f8f',padding:20}}
); 
