import { Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useAuth } from '../../src/auth/AuthContext';

export default function Profile(){
 const {user,logout}=useAuth(); const creator=user?.role==='creator';
 const open=(path:string)=>Linking.openURL(`https://mybeathub.com${path}`);
 return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.container}>
  <Text style={s.title}>Profile</Text><View style={s.card}><Text style={s.name}>{user?.stage_name||user?.username}</Text><Text style={s.email}>{user?.email}</Text><Text style={s.role}>{user?.role}</Text></View>
  {creator&&<><Text style={s.section}>Creator</Text><Pressable style={s.row} onPress={()=>router.push('/creator-dashboard')}><Text style={s.rowText}>Creator Studio</Text><Text style={s.arrow}>›</Text></Pressable><Pressable style={s.row} onPress={()=>router.push('/creator-profile')}><Text style={s.rowText}>Edit creator profile</Text><Text style={s.arrow}>›</Text></Pressable><Pressable style={s.row} onPress={()=>router.push('/creator-upload')}><Text style={s.rowText}>Upload Beat / Track</Text><Text style={s.arrow}>›</Text></Pressable><Pressable style={s.row} onPress={()=>router.push('/creator-finances')}><Text style={s.rowText}>Sales & withdrawals</Text><Text style={s.arrow}>›</Text></Pressable></>}
  <Text style={s.section}>Account</Text><Pressable style={s.row} onPress={()=>router.push('/notifications')}><Text style={s.rowText}>Notifications</Text><Text style={s.arrow}>›</Text></Pressable><Pressable style={s.row} onPress={()=>open('/forgot-password')}><Text style={s.rowText}>Change password</Text><Text style={s.arrow}>↗</Text></Pressable>
  <Text style={s.section}>BeatHub</Text><Pressable style={s.row} onPress={()=>open('/support')}><Text style={s.rowText}>Help & support</Text><Text style={s.arrow}>↗</Text></Pressable><Pressable style={s.row} onPress={()=>open('/terms')}><Text style={s.rowText}>Terms</Text><Text style={s.arrow}>↗</Text></Pressable><Pressable style={s.row} onPress={()=>open('/privacy')}><Text style={s.rowText}>Privacy</Text><Text style={s.arrow}>↗</Text></Pressable>
  <Pressable style={s.logout} onPress={async()=>{await logout();router.replace('/(auth)/login')}}><Text style={s.logoutText}>Sign out</Text></Pressable><Text style={s.version}>BeatHub mobile · v1.0.0</Text>
 </ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#0d0b12'},container:{padding:24,paddingBottom:50},title:{fontSize:30,fontWeight:'800',color:'#fff',marginTop:15,marginBottom:22},card:{backgroundColor:'#181520',borderRadius:18,padding:20},name:{color:'#fff',fontSize:21,fontWeight:'700'},email:{color:'#918b9b',marginTop:7},role:{color:'#fff',marginTop:14,textTransform:'capitalize'},section:{color:'#918b9b',fontSize:12,fontWeight:'800',letterSpacing:1.2,marginTop:26,marginBottom:8},row:{flexDirection:'row',alignItems:'center',paddingVertical:15,borderBottomWidth:1,borderBottomColor:'#211d28'},rowText:{color:'#fff',fontSize:15,flex:1},arrow:{color:'#918b9b',fontSize:22},logout:{marginTop:30,padding:16,borderRadius:12,borderWidth:1,borderColor:'#4b3038',alignItems:'center'},logoutText:{color:'#ffb0b0',fontWeight:'700'},version:{color:'#5f5968',textAlign:'center',fontSize:12,marginTop:18}});
